spring.application.name=khilat

# ===============================
# Database Configuration (Neon)
# ===============================

spring.datasource.url=jdbc:postgresql://ep-bold-glade-ahpvmzeh-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_mIFVP12lyfgT

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Connection Pool (HikariCP)
# ===============================

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000



spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Keep framework logs clean
logging.level.root=INFO

# Enable DEBUG only for your application
logging.level.e_commerce.khilat=DEBUG


logging.file.name=logs/api.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n



